spring:
  jms:
    listener:
      acknowledge-mode: client
      concurrency: 5
      max-concurrency: 10
  activemq:
    broker-url: tcp://localhost:61616
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///car_service
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
#  redis:
#    # redis所在的服务器地址
#    host: 192.168.1.40
#    port: 6379

mybatis:
  # entity的位置
  type-aliases-package: com.kaishengit.entity
  # 大小写转换并使用驼峰命名法
  configuration:
    map-underscore-to-camel-case: true
  # mapper.xml的位置
  mapper-locations: classpath:mapper/*.xml

# 设置mapper的日志级别,方便查看输出的sql语句
logging:
  level:
    com:
      kaishengit:
        mapper: debug

redisson:
  # 设置服务器地址及端口
  host: redis://192.168.0.40:6379
  timeout: 5000